import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';

function tokenDir() {
    return process.env.RUNNER_VNC_TOKEN_DIR ?? './tmp/vnc-tokens';
}

/**
 * Starts an isolated Xvfb display + x11vnc process for one session, on
 * Linux only. A single, long-lived, Supervisor-managed websockify process
 * (docs/samples/supervisor-savv-websockify.conf) is the only thing Nginx
 * ever proxies (see docs/deployment-ubuntu.md) - it multiplexes many
 * sessions using its TokenFile plugin, looking up "127.0.0.1:<vncPort>" by
 * the view token in a small file this module writes/removes per session.
 * The per-session VNC port itself is never exposed publicly.
 *
 * Uses safe argument arrays throughout (no shell string concatenation with
 * user/page-derived input) and never runs any of these processes as root.
 */
export function startStreamingStack({ displayNumber }) {
    if (typeof process.getuid === 'function' && process.getuid() === 0) {
        throw new Error('Refusing to start the streaming stack as root.');
    }

    const displayArg = `:${displayNumber}`;
    // Each session needs its own VNC port, distinct from every other
    // concurrent session's - derive it from the (already-unique) display
    // number rather than relying on x11vnc's default (which collides).
    const vncPort = 5900 + displayNumber;

    const xvfb = spawn('Xvfb', [displayArg, '-screen', '0', '1280x800x24', '-nolisten', 'tcp'], {
        stdio: 'ignore',
    });

    const x11vnc = spawn('x11vnc', [
        '-display', displayArg,
        '-rfbport', String(vncPort),
        '-localhost',
        '-nopw',
        '-forever',
        '-shared',
        '-quiet',
    ], { stdio: 'ignore' });

    const processes = [xvfb, x11vnc];

    return {
        displayEnv: displayArg,
        vncPort,
        stop() {
            for (const p of processes) {
                if (!p.killed) p.kill('SIGTERM');
            }
        },
    };
}

/**
 * Registers a view token with the shared websockify broker: viewers who
 * connect to wss://<domain>/rbi/?token=<token> get proxied to this
 * session's VNC port. Call this each time ImportSession::issueViewToken()
 * issues a new raw token, and removeVncToken() when it expires or the
 * session stops - a stale token file would let an old link keep working.
 */
export async function writeVncToken(token, vncPort) {
    await fs.mkdir(tokenDir(), { recursive: true });
    await fs.writeFile(tokenPath(token), `127.0.0.1:${vncPort}\n`, { mode: 0o600 });
}

export async function removeVncToken(token) {
    await fs.rm(tokenPath(token), { force: true });
}

function tokenPath(token) {
    // Tokens are generated by Str::random(48) (alphanumeric) on the Laravel
    // side - reject anything else so this can never be used as a path
    // traversal primitive even if that assumption is ever violated.
    if (!/^[A-Za-z0-9]{16,64}$/.test(token)) {
        throw new Error('Refusing to write a VNC token file for a malformed token.');
    }

    return path.join(tokenDir(), token);
}
